use_frameworks!
platform :ios, "8.0"
xcodeproj 'WUYINGDENGXIA.xcodeproj'
target "WUYINGDENGXIA" do
pod "AFNetworking"
pod "ZYBannerView"
pod "Masonry"
pod "MJRefresh"
pod "SDWebImage"
pod "TMCache"
pod "MBProgressHUD"
pod "JTCalendar"
pod "FMDB"
pod "CYLTabBarController"
pod "IQKeyboardManager"

end

